name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  CI:
    uses: vslovik/actions/.github/workflows/python.yml@master
    secrets: inherit
    with:
      python-version: '3.9'